#####################
# easyvote Education
#####################
-
  name: 'PanelHostView'
  uriPattern: 'votings/{actionarguments}'
  defaults:
    '@package':    'Visol.Easyvote_education'
    '@plugin':     'Managepanels'
    '@controller': 'Panel'
    '@action':     'votingStep'
  httpMethods: ['GET']
