#####################
# easyvote Education
#####################
-
  name: 'PanelHostView'
  uriPattern: 'votings/{actionarguments}'
  defaults:
    '@package':    'Visol.Easyvote_education'
    '@plugin':     'Managepanels'
    '@controller': 'Panel'
    '@action':     'votingStep'
  httpMethods: ['GET']
-
  name: 'GuestView'
  uriPattern: 'guestview/{panel}'
  defaults:
    '@package':    'Visol.Easyvote_education'
    '@plugin':     'Guestview'
    '@controller': 'Panel'
    '@action':     'guestViewEventStream'
  httpMethods: ['GET']
